name: Output info
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "GitHub Context ${{ toJson(github) }}"